// ══════════════════════════════════════════════════════════════════
// RÉFÉRENCE DE L'ANCIEN INDEX VALIDÉ
// ══════════════════════════════════════════════════════════════════
//
// Relevé mécanique des libellés <label> de l'ancien index validé
// (le fichier de référence fourni par le propriétaire, 17 189 lignes).
// Ce fichier n'est PAS une base de développement : il ne sert qu'à
// prouver que les formulaires historiques n'ont pas été appauvris.
//
// Extraction : contenu textuel de chaque <label>…</label>, balises
// retirées, espaces normalisés, entités &nbsp; et &amp; résolues, et
// blocs de plus de 120 caractères écartés (ils viennent de feuilles de
// style, pas de formulaires). Doublons fusionnés.
//
// Toute disparition non listée dans DISPARUS_EXPLIQUES fait échouer la
// section O de tests/t_stabilisation.js.

const LIBELLES_ANCIEN_INDEX = [
  "Achat de véhicule (garage / particulier)",
  "Adresse e-mail *",
  "Adresse postale *",
  "Adresse postale de restitution *",
  "Adresse' + R + '",
  "Autre",
  "Cette mission inclut une restitution du véhicule",
  "Client",
  "Code parrainage (optionnel)",
  "Code postal *",
  "Code postal' + R + '",
  "Combien de véhicules sont concernés ? *",
  "Comment avez-vous connu HelixCar ? *",
  "Comment les véhicules arrivent-ils chez HelixCar ? i *",
  "Comment pouvons-nous vous accompagner ? *",
  "Consignes de restitution (facultatif)",
  "Contact (facultatif)",
  "Contraintes particulières (facultatif)",
  "Convoyage automobile",
  "Convoyage par la route",
  "Convoyeur",
  "Créneau",
  "Créneau horaire",
  "Dans les locaux de votre entreprise",
  "Date de début du stockage i *",
  "Date de fin prévue i *",
  "Date de livraison *",
  "Date de prise en charge *",
  "Date de restitution *",
  "Date' + R + '",
  "De",
  "Documents requis",
  "Début du créneau *",
  "Délai souhaité i *",
  "Déménagement / déplacement personnel",
  "Email",
  "Email *",
  "Email du filleul *",
  "Expérience de conduite * (permis minimum 3 ans obligatoire)",
  "Fin du créneau *",
  "Flexible",
  "HelixCar me livre les véhicules",
  "HelixCar vient les récupérer",
  "Heure d'entrée prévue *",
  "Heure de récupération *",
  "Heure de récupération prévue *",
  "Heure précise",
  "Heure souhaitée *",
  "Horaire de livraison *",
  "Horaire de prise en charge *",
  "Horaire de restitution *",
  "Horaire' + R + '",
  "Immatriculation",
  "Immatriculation (facultatif)",
  "Informations complémentaires (facultatif)",
  "Informations complémentaires (optionnel)",
  "Je dispose d'un emplacement accessible et adapté au nettoyage des véhicules.",
  "Je les dépose moi-même",
  "Je souhaite simplement créer mon compte pour l'instant",
  "Je souhaite être conseillé",
  "Je souhaite être recontacté pour compléter les informations de ma flotte automobile",
  "Je suis…",
  "Je viens récupérer les véhicules",
  "Les véhicules suivent-ils la même organisation ? i *",
  "Livraison à une adresse différente",
  "Marque / Modèle *",
  "Marque / modèle",
  "Marque / modèle *",
  "Mode de transport i *",
  "Mot de passe *",
  "Motif de la demande *",
  "Nettoyage automobile",
  "Nettoyage automobile professionnel Réservé aux entreprises",
  "Nettoyage extérieur",
  "Nettoyage intérieur",
  "Nom",
  "Nom *",
  "Nom de la société *",
  "Nom et prénom du contact sur place (facultatif)",
  "Nom et prénom du contact à la livraison (facultatif)",
  "Nom et prénom — réceptionnaire (facultatif)",
  "Nombre approximatif de véhicules *",
  "Non",
  "Non, certains véhicules ont un trajet différent",
  "Numéro de téléphone *",
  "N° SIRET *",
  "N° de châssis (VIN) (facultatif)",
  "N° de châssis (VIN) — véhicule restitution (facultatif)",
  "Oui",
  "Oui, mêmes adresses et mêmes horaires",
  "Où doit avoir lieu le nettoyage ? *",
  "Permis de conduire — PDF, JPG ou PNG",
  "Pièce d'identité — PDF, JPG ou PNG",
  "Plaque *",
  "Plaque d'immatriculation (facultatif)",
  "Prioritaire",
  "Prioritaire / urgent",
  "Précisez *",
  "Précisez la catégorie *",
  "Précisez la raison de votre convoyage *",
  "Prénom",
  "Prénom *",
  "Préparation complète — intérieur et extérieur",
  "Que souhaitez-vous après le stockage ? i *",
  "Quel délai souhaitez-vous ? *",
  "Quel nettoyage souhaitez-vous ? *",
  "Quelle est la date souhaitée ? *",
  "Quelle est votre disponibilité ? *",
  "Quelles activités souhaitez-vous exercer avec HelixCar ? *",
  "RC Pro en cours de validité — PDF, JPG ou PNG",
  "Renfort automobile",
  "Retour au lieu de départ",
  "Répartition par catégorie *",
  "Standard",
  "Stockage automobile i",
  "Sur votre parc automobile",
  "Transport professionnel (flotte / entreprise)",
  "Transport sur plateau",
  "Trouver un professionnel automobile",
  "Type",
  "Type *",
  "Type de client *",
  "Type de trajet",
  "Type de trajet retour *",
  "Type de véhicule (restitution) *",
  "Type de véhicule *",
  "Téléphone (facultatif)",
  "Téléphone *",
  "Téléphone du contact (facultatif)",
  "Téléphone du filleul",
  "Téléphone — réceptionnaire (facultatif)",
  "Une arrivée d'eau et une prise électrique fonctionnelle sont disponibles à proximité.",
  "VIN (facultatif)",
  "Vente de véhicule",
  "Ville *",
  "Ville' + R + '",
  "Votre message *",
  "Votre numéro client (si vous en avez un)",
  "urgence",
  "À"
];

// Les quatorze libellés de l'ancien index qui n'existent plus dans l'index
// actuel. Chacun a une raison NOMMÉE et vérifiable. Aucun n'est une
// perte de fonctionnalité historique : ce sont soit des retraits
// explicitement demandés, soit des remplacements par un dispositif
// plus riche apporté par le main courant.
const DISPARUS_EXPLIQUES = [
  ['Quelle est votre disponibilité ? *',
    'retrait explicitement demandé (§ 11 du chantier) — la question et ses trois choix'],
  ['Heure souhaitée *',
    'retrait explicitement demandé — champ de la branche « Heure précise »'],
  ['Créneau horaire',
    'retrait explicitement demandé — choix de la question « disponibilité »'],
  ['Flexible',
    'retrait explicitement demandé — choix de la question « disponibilité »'],
  ['Début du créneau *',
    'devenu FACULTATIF : « Début (facultatif) », la plage horaire ne bloque plus'],
  ['Fin du créneau *',
    'devenu FACULTATIF : « Fin (facultatif) », la plage horaire ne bloque plus'],
  ['Quelle est la date souhaitée ? *',
    'remplacé par une PÉRIODE : « Date de début » et « Date de fin » (§ 11)'],
  ['Mode de transport i *',
    'contrôle GLOBAL explicitement à supprimer — la question vit désormais dans '
    + 'chaque fiche véhicule, rendue par .veh-sstitre et non par un <label>'],
  ['Quelles activités souhaitez-vous exercer avec HelixCar ? *',
    'remplacé par la liste des huit métiers de la PR nº 2 (METIERS_PARTENAIRE), '
    + 'plus riche que les trois cases historiques'],
  ['Nettoyage automobile',
    'ancienne case d\'activité partenaire — devenue le métier « Nettoyage » '
    + 'de METIERS_PARTENAIRE'],
  ['Renfort automobile',
    'ancienne case d\'activité partenaire — devenue les métiers « Renfort », '
    + '« Accueil en concession », « Préparation automobile », « Opérations de parc » '
    + 'et « Soutien administratif »'],
  ['RC Pro en cours de validité — PDF, JPG ou PNG',
    'libellé remplacé par un statut dynamique : obligatoire pour le convoyage, '
    + 'facultative pour les autres métiers'],
  ['Pièce d\'identité — PDF, JPG ou PNG',
    'libellé renforcé par un astérisque visible : ce document est obligatoire'],
  ['Permis de conduire — PDF, JPG ou PNG',
    'libellé renforcé par un astérisque visible : ce document est obligatoire']
];

module.exports = { LIBELLES_ANCIEN_INDEX, DISPARUS_EXPLIQUES };
