const fs=require('fs');
module.exports=async({db,rpc,check,rejected,admin})=>{
 await db.exec(`alter table demande_informations_manquantes add column transmise_le timestamptz;alter table demande_informations_manquantes add column id uuid default gen_random_uuid();
 create or replace function est_proprietaire_demande(p uuid) returns boolean language sql stable as $$select exists(select 1 from clients where id=p and auth_user_id=auth.uid())$$;`);
 await db.exec(fs.readFileSync('supabase/migrations/20260926181205_relecture_client_suivi_admin.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20260926182606_empreinte_preparation_sans_verrou_client.sql','utf8'));
 const cid='11112222-1111-1111-1111-111111111111',uid='22223333-1111-1111-1111-111111111111';
 await db.exec(`insert into clients(id,auth_user_id,numero_client,code_parrainage,nom,prenom,email,type_client,type_service,nb_vehicules,trajet_commun) values('${cid}','${uid}','QA-RELECTURE','QA-RELECTURE','QA','Client','qa@example.test','particulier','convoyage',2,false);
 insert into devis(id,client_id,reference,prix,statut,paiement_statut)values(gen_random_uuid(),'${cid}','DEV-RELECTURE',500,'accepte','paye');
 insert into vehicules(id,dossier_id,position,marque_modele,type_vehicule,vin,immatriculation,motorisation,adresse_depart_rue,ville_depart,adresse_arrivee_rue,ville_arrivee,date_prise_en_charge,date_livraison,heure_prise_en_charge,heure_livraison,pc_contact_nom,pc_contact_tel,liv_contact_nom,liv_contact_tel,restitution_concernee)
 select gen_random_uuid(),'${cid}',n,'Peugeot 308','berline','VF12345678901234'||n,'AB-123-C'||n,'Diesel','12 rue Départ','Paris','13 rue Arrivée','Lyon','2026-11-01','2026-11-01','09:00','16:00','Ancien contact','0600000000','Livraison','0600000001',false from generate_series(1,2)n;
 select set_config('request.jwt.claim.sub','${admin}',false);`);
 const before=await rpc('source_preparation_missions',[cid]);
 await db.exec(`update clients set informations_confirmees_le=now() where id='${cid}'`);
 check('Confirmation seule conserve la préparation',before.empreinte===(await rpc('source_preparation_missions',[cid])).empreinte);
 await db.exec(`update clients set informations_confirmees_le=null where id='${cid}';select set_config('request.jwt.claim.sub','${uid}',false)`);
 let rows=(await db.query('select * from informations_demande($1)',[cid])).rows;
 check('Valeurs source VIN, modèle et adresse visibles',rows.find(r=>r.cle==='vehicule_1_marque_modele').valeur==='Peugeot 308'&&rows.find(r=>r.cle==='vehicule_1_adresse_depart').valeur==='12 rue Départ');
 check('Première relecture ouverte',!(await rpc('contexte_completion_demande',[cid])).verrouillee);
 await rejected('Adresse déjà fournie verrouillée',()=>rpc('repondre_informations_demande',[cid,JSON.stringify({vehicule_1_adresse_depart:'Nouvelle adresse',vehicule_1_vin:'VF333333333333333'})]));
 await rejected('Nombre de véhicules interdit',()=>rpc('repondre_informations_demande',[cid,'{"nb_vehicules":"3"}']));
 await rejected('Motorisation connue verrouillée',()=>rpc('repondre_informations_demande',[cid,'{"vehicule_1_motorisation":"Essence"}']));
 const changes={vehicule_1_vin:'VF333333333333333',vehicule_1_contact_pc_nom:'Nouveau contact',vehicule_1_consignes:'Clés à l’accueil'};
 await rpc('repondre_informations_demande',[cid,JSON.stringify(changes)]);
 check('Confirmation verrouille le dossier',(await rpc('contexte_completion_demande',[cid])).verrouillee);
 const review=(await db.query('select * from demande_informations_manquantes where client_id=$1',[cid])).rows;
 check('Admin reçoit avant et après',review.find(r=>r.cle==='vehicule_1_contact_pc_nom').ancienne_valeur==='Ancien contact'&&review.find(r=>r.cle==='vehicule_1_contact_pc_nom').valeur==='Nouveau contact');
 check('Autre véhicule intact',(await db.query('select vin from vehicules where dossier_id=$1 and position=2',[cid])).rows[0].vin==='VF123456789012342');
 await rejected('Correction libre impossible après confirmation',()=>rpc('repondre_informations_demande',[cid,'{"vehicule_1_vin":"VF444444444444444"}']));
 await rpc('repondre_informations_demande',[cid,JSON.stringify(changes)]);
 check('Rejeu ne duplique pas les réponses',(await db.query('select count(*)::int as n from demande_informations_manquantes where client_id=$1',[cid])).rows[0].n===3);
 await db.exec(`select set_config('request.jwt.claim.sub','${admin}',false);update demande_informations_manquantes set statut='a_corriger',commentaire='Vérifiez le VIN' where client_id='${cid}' and cle='vehicule_1_vin';select set_config('request.jwt.claim.sub','${uid}',false);`);
 await rpc('repondre_informations_demande',[cid,'{"vehicule_1_vin":"VF555555555555555"}']);
 check('Correction renvoyée distinguée',(await db.query("select correction_recue,commentaire from demande_informations_manquantes where client_id=$1 and cle='vehicule_1_vin'",[cid])).rows[0].correction_recue);
 await db.exec(`select set_config('request.jwt.claim.sub','${admin}',false);update demande_informations_manquantes set statut='validee' where client_id='${cid}';`);
 const after=await rpc('source_preparation_missions',[cid]);
 check('VIN et contact validés synchronisés',after.vehicules.find(v=>v.position===1).vin==='VF555555555555555'&&after.vehicules.find(v=>v.position===1).pc_contact_nom==='Nouveau contact');
 check('Consignes validées synchronisées',after.vehicules.find(v=>v.position===1).consignes==='Clés à l’accueil');
 check('Empreinte préparation mise à jour',before.empreinte!==after.empreinte);
 await rejected('Ancienne préparation refusée',()=>rpc('enregistrer_preparation_missions',[cid,before.empreinte,'[]']));
 await db.exec(`select set_config('request.jwt.claim.sub','33334444-1111-1111-1111-111111111111',false)`);
 await rejected('Autre client refusé',()=>rpc('contexte_completion_demande',[cid]));
 await rejected('Autre client ne modifie pas le dossier',()=>rpc('repondre_informations_demande',[cid,'{}']));
};
