const L=require('./lib');
(async()=>{const b=await L.launch();try{for(const width of [390,1280]){const p=await L.newPage(b);await p.setViewportSize({width,height:1000});await L.fillStep1(p,'particulier');await L.chooseService(p,'convoyage');for(const service of ['convoyage','stockage']){
const r=await p.evaluate(service=>{const set=(id,v)=>document.getElementById(id).value=v;const get=id=>document.getElementById(id).value;const radio=(n,v)=>{const e=document.querySelector('input[name="'+n+'"][value="'+v+'"]');if(e)e.checked=true;};
radio('type-service',service);radio('stock-acheminement','helixcar');radio('stock-sortie','helixcar');set('stock-debut','2027-10-13');set('stock-fin','2027-10-30');set('nb-vehicules','2');rendreFichesVehicules();radio('veh-0-liv-active','oui');radio('veh-0-restit-active','oui');basculerRestitVehicule(0);
set('veh-0-pc-date','2027-10-13');set('veh-0-liv-date','2027-10-30');set('veh-0-restit-date','2027-10-31');radio('veh-0-restit-htype','precise');radio('veh-0-pc-htype','precise');radio('veh-0-liv-htype','creneau');set('veh-0-liv-cdeb','14:30');set('veh-0-liv-cfin','16:45');set('veh-0-restit-heure','09:00');
function open(){_hcFermerCalendrier();_hcOuvrirCalendrier(document.getElementById('veh-0-restit-date'));_hcCalAnneeAffichee=2027;_hcCalMoisAffiche=9;_hcRendreCalendrier();}
open();const r={};r.dayEnabled=!document.querySelector('[data-jour="30"]').disabled;r.renderDoesNotWrite=get('veh-0-restit-heure')==='09:00';document.querySelector('[data-jour="30"]').click();r.adjusted=get('veh-0-restit-date')==='2027-10-30'&&get('veh-0-restit-heure')==='17:00';r.siblingsUnchanged=get('veh-0-liv-cfin')==='16:45'&&get('veh-0-liv-cdeb')==='14:30';r.staysOpen=!!_hcCalChampActif;r.quiet=document.getElementById('hc-cal-chrono-note').hidden;
_hcSelectionnerJour(31);r.nextDayPreserves=get('veh-0-restit-heure')==='17:00';set('veh-0-restit-heure','18:00');open();_hcSelectionnerJour(30);r.validPreserved=get('veh-0-restit-heure')==='18:00';
set('veh-0-restit-date','2027-10-31');radio('veh-0-restit-htype','creneau');set('veh-0-restit-cdeb','09:00');set('veh-0-restit-cfin','10:30');open();_hcSelectionnerJour(30);r.rangeShift=get('veh-0-restit-cdeb')==='17:00'&&get('veh-0-restit-cfin')==='18:30';
set('veh-0-pc-heure','18:00');_hcFermerCalendrier();_hcOuvrirCalendrier(document.getElementById('veh-0-pc-date'));_hcCalAnneeAffichee=2027;_hcCalMoisAffiche=9;_hcRendreCalendrier();_hcSelectionnerJour(30);if(service==='convoyage')r.pickupAdjusted=get('veh-0-pc-date')==='2027-10-30'&&get('veh-0-pc-heure')==='14:15';else r.storagePickupInherited=get('veh-0-pc-date')==='2027-10-13';r.deliveryKept=get('veh-0-liv-cdeb')==='14:30';
set('veh-0-restit-date','2027-10-31');set('veh-0-liv-cfin','23:50');open();_hcSelectionnerJour(30);r.impossibleBlocked=get('veh-0-restit-date')==='2027-10-31'&&get('veh-0-restit-cdeb')==='17:00';_hcSelectionnerJour(29);r.dateOrderBlocked=get('veh-0-restit-date')==='2027-10-31';_hcFermerCalendrier();return r;
},service);for(const [k,v]of Object.entries(r))L.check(width+' '+service+' '+k,v);}await p.close();}}finally{await b.close();}process.exitCode=L.results()?1:0;})().catch(e=>{console.error(e);process.exitCode=1;});
