const fs=require('fs'),assert=require('assert');
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
(async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema private;
 create table auth.users(id uuid primary key,email text,deleted_at timestamptz);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function public.est_admin() returns boolean language sql stable as $$select auth.uid()='11111111-1111-4111-8111-111111111111'::uuid$$;
 grant usage on schema public,auth to anon,authenticated;`);
 const fixture=JSON.parse(fs.readFileSync(__dirname+'/preparation/schema.json'));
 for(const t of fixture.tables.filter(t=>['clients','vehicules'].includes(t.name))) await db.exec('create table public.'+t.name+'('+t.columns.map(c=>'"'+c.name+'" '+c.type+(c.default?' default '+c.default:'')+(c.notnull?' not null':'')).join(',')+',primary key(id))');
 await db.exec(fs.readFileSync('migrations/92_creation_demande_atomique.sql','utf8'));
 const admin='11111111-1111-4111-8111-111111111111',client='22222222-2222-4222-8222-222222222222',other='33333333-3333-4333-8333-333333333333';
 for(const u of [admin,client,other])await db.query('insert into auth.users values($1,$2,null)',[u,u+'@example.test']);
 await db.query("insert into clients(id,auth_user_id,numero_client,code_parrainage,prenom,nom,email,type_client) values(gen_random_uuid(),$1,'HC-OLD','PAR-OLD','Alice','Client','old@example.test','particulier'),(gen_random_uuid(),$1,'HC-OLD2','PAR-OLD2','Alice','Client','old@example.test','particulier')",[client]);
 const migration=fs.readdirSync('supabase/migrations').find(f=>f.endsWith('_numeros_clients_demandes_admin.sql'));
 await db.exec(fs.readFileSync('supabase/migrations/'+migration,'utf8'));
 let count=0;const ok=(name,v)=>{assert(v,name);count++;console.log('PASS '+name)};
 const q=async(sql,p)=>(await db.query(sql,p)).rows;
 const as=async uid=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);
 const rejected=async(name,f)=>{try{await f()}catch(e){ok(name,true);return}throw Error('Not rejected: '+name)};
 const rows=await q('select * from comptes_clients');ok('un compte malgré deux demandes',rows.length===1);const numero=rows[0].numero;
 ok('cinq caractères aléatoires lisibles',/^CLI-[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{5}$/.test(numero));
 await as(admin);const rpc=async(name,args)=>(await q('select public.'+name+'('+args.map((_,i)=>'$'+(i+1)).join(',')+') as r',args))[0].r;
 const found=await rpc('rechercher_compte_client_admin',[numero.toLowerCase()]);ok('identité retrouvée et email auth canonique',found.profil.nom==='Client'&&found.profil.email===client+'@example.test');
 const id='44444444-4444-4444-8444-444444444444';const p={id,numero_client:'HC-NEW',code_parrainage:'PAR-NEW',type_service:'convoyage',prenom:'FORGED',email:'forged@example.test',auth_user_id:other,statut:'paye'};
 const args=[numero,JSON.stringify(p),JSON.stringify([{position:1,marque_modele:'TEST',dossier_id:'55555555-5555-4555-8555-555555555555'}]),'x'.repeat(48)];
 await rpc('creer_demande_admin',args);
 const saved=(await q('select * from clients where id=$1',[id]))[0];
 ok('rattachée au client et non à admin ni tiers',saved.auth_user_id===client);ok('identité imposée serveur',saved.prenom==='Alice');ok('statut nouveau imposé',saved.statut==='nouveau');
 ok('véhicule lié atomiquement',(await q('select * from vehicules where dossier_id=$1',[id])).length===1);
 ok('audit admin',(await q('select admin_id from demandes_saisies_admin where demande_id=$1',[id]))[0].admin_id===admin);
 ok('rejeu idempotent',(await rpc('creer_demande_admin',args)).deja_existante===true);
 await rejected('mauvaise preuve refusée',()=>rpc('creer_demande_admin',[...args.slice(0,3),'y'.repeat(48)]));
 await rejected('rollback véhicule invalide',()=>rpc('creer_demande_admin',[numero,JSON.stringify({...p,id:'55555555-5555-4555-8555-555555555555',numero_client:'HC-FAIL'}),'[3]','x'.repeat(48)]));
 ok('aucune demande partielle',(await q("select * from clients where numero_client='HC-FAIL'")).length===0);
 await as(client);await db.exec('set role authenticated');
 ok('client lit son numéro',(await q('select * from comptes_clients')).length===1);
 await rejected('lookup interdit au client',()=>rpc('rechercher_compte_client_admin',[numero]));
 await rejected('création admin interdite au client',()=>rpc('creer_demande_admin',args));
 await rejected('numéro non modifiable par client',()=>db.exec("update comptes_clients set numero='CLI-AAAAA'"));
 await db.exec('reset role');await as(other);await db.exec('set role authenticated');ok('numéro tiers caché',(await q('select * from comptes_clients')).length===0);await db.exec('reset role');
 await rpc('creer_demande_avec_vehicules',[JSON.stringify({id:'66666666-6666-4666-8666-666666666666',prenom:'Public',nom:'Client',numero_client:'HC-PUBLIC',code_parrainage:'PAR-PUBLIC',email:'test@example.test',type_service:'convoyage'}),'[]','z'.repeat(48),null]);
 ok('parcours client existant conserve son propriétaire',(await q("select auth_user_id from clients where numero_client='HC-PUBLIC'"))[0].auth_user_id===other);
 ok('nouveau compte reçoit numéro',(await q('select * from comptes_clients where auth_user_id=$1',[other])).length===1);
 await as(null);await db.exec('set role anon');await rejected('aucune lecture anonyme',()=>q('select * from comptes_clients'));
 await db.close();console.log(count+' vérifications SQL réussies');
})().catch(e=>{console.error(e);process.exit(1)});
