const assert=require('assert'),L=require('./lib'),{urlFichier}=require('./env');const planner=require('../assets/preparation-missions.js');
const v={id:'veh-1',position:1,type_vehicule:'berline',marque_modele:'Peugeot 308',immatriculation:'SECRET-PLATE',vin:'SECRET-VIN',adresse_depart_rue:'12 rue Secrète',adresse_arrivee_rue:'10 rue Cachée',ville_depart:'Paris',ville_arrivee:'Lyon',date_prise_en_charge:'2026-11-08',date_livraison:'2026-11-10',heure_prise_en_charge:'09:00',heure_livraison:'15:00',restitution_concernee:true,restit_marque_modele:'Audi A3',restit_ville:'Dijon',restit_date:'2026-11-10',restit_heure_type:'creneau',restit_creneau_debut:'16:00',restit_creneau_fin:'17:00',restit_contraintes:'Clefs secrètes',restit_immatriculation:'SECRET-RESTIT'};
const c={id:'client-1',type_service:'convoyage',type_client:'professionnel',societe:'SECRET-SOCIETE',notes:'SECRET-NOTE',stockage_date_debut:'2026-11-08',stockage_date_fin:'2026-11-13',stockage_acheminement:'helixcar',stockage_sortie:'helixcar'};
(async()=>{
 for(const [days,count] of [[0,1],[1,1],[2,1],[3,2],[5,2]]){const x=planner.build(c,[{...v,date_livraison:'2026-11-'+String(8+days).padStart(2,'0')}]);L.check('Seuil automatique '+days+' jours',x.length===count);if(days>2)L.check('Restitution sur le trajet final seulement',!x[0].mission.restitution&&x[1].mission.restitution);}
 for(const [inMode,outMode,n] of [['client','client',0],['helixcar','client',1],['client','helixcar',1],['helixcar','helixcar',2]]){const x=planner.build({...c,type_service:'stockage',stockage_acheminement:inMode,stockage_sortie:outMode},[v]);L.check('Stockage '+inMode+'/'+outMode,x.length===n);}
 const override=planner.build({...c,type_service:'stockage'},[{...v,livraison_apres_stockage:false}]);L.check('Choix individuel sans livraison respecté',override.length===1&&override[0].kind==='avant_stockage');
 const p=planner.build(c,[v])[0];L.check('Consignes restitution administratives conservées',p.mission.restit_info==='Clefs secrètes');L.check('Projection publique sans données privées',!JSON.stringify(planner.publicData(p)).includes('SECRET')&&!JSON.stringify(planner.publicData(p)).includes('rue'));
 L.check('Tiret entre horaires',planner.publicData(p).rows.some(r=>r.value.includes('16:00 - 17:00')));
 const clean={...c,type_service:'nettoyage',nettoyage_details:{type_nettoyage:'interieur_exterieur',nombre_vehicules_approx:4,adresse_ville:'Créteil',date_souhaitee:'2026-11-08',date_fin:'2026-11-08',creneau_debut:'09:00',creneau_fin:'12:00'}};
 const prof={...c,type_service:'professionnel',professionnel_details:{categorie:'technicien',specialite:'diagnostic',nombre_professionnels:2,adresse_ville:'Nanterre',date_debut:'2026-11-08',date_fin:'2026-11-09',heure_debut:'09:00',heure_fin:'17:00'}};
 for(const sample of [clean,prof]){const x=planner.build(sample,[])[0];L.check(sample.type_service+' : pas de trajet artificiel',x.kind==='intervention'&&!('ville_depart' in x.mission));L.check(sample.type_service+' : données préremplies',x.rows.some(r=>r.value.includes('09:00 - ')));}
 L.check('Professionnels : métier et nombre repris',planner.build(prof,[])[0].category==='technicien'&&planner.build(prof,[])[0].nb_professionnels===2);
 const browser=await L.launch();try{for(const width of [390,1280]){const page=await browser.newPage({viewport:{width,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:null}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},rpc:async()=>({data:null})})};});await page.goto(urlFichier('dashboard.html'));
 await page.evaluate(({c,v})=>{window.__calls=[];window.__source={client:c,vehicules:[v],devis_id:'dv1',reference:'DEV-QA',empreinte:'hash',brouillons:[]};sbAuth.rpc=async(name,args)=>{__calls.push(name);if(name==='source_preparation_missions')return {data:__source};if(name==='enregistrer_preparation_missions'){__source.brouillons=args.p_plans.map((p,i)=>({id:'p'+i,cle:p.key,empreinte:'hash',plan:p,annonce:p.public}));return {data:__source};}throw Error('Publication interdite dans ce test');};document.getElementById('login-screen').style.display='none';_devisParClient[c.id]={statut:'accepte',paiement_statut:'paye'};}, {c,v});
 const button=await page.evaluate(c=>_blocDevisHtml(c),c);L.check(width+' bouton depuis devis payé',button.includes('Préparer les missions'));
 await page.evaluate(()=>ouvrirPreparationDemande('client-1'));L.check(width+' ouverture sans mutation',await page.evaluate(()=>__calls.join()==='source_preparation_missions'));
 await page.locator('[data-field="remuneration"]').fill('250');await page.locator('[data-field="distance"]').fill('465');await page.locator('[data-field="motorisation"]').selectOption('Hybride');await page.locator('[data-field="restit_motorisation"]').selectOption('Essence');await page.locator('[data-prep-view="preview"]').first().click();
 const content=await page.locator('#hc-prep-body').innerText();L.check(width+' aperçu filtré avec prix total',content.includes('250')&&!content.includes('SECRET')&&!content.includes('rue'));
 L.check(width+' aperçu ne publie pas',await page.evaluate(()=>!__calls.includes('publier_preparation_mission')));
 await page.locator('#hc-prep-close').click();await page.evaluate(()=>ouvrirPreparationDemande('client-1'));L.check(width+' brouillon retrouvé',await page.locator('[data-field="remuneration"]').inputValue()==='250');
 L.check(width+' sans débordement',await page.locator('#modal-preparation-missions .hc-prep-modal').evaluate(e=>e.scrollWidth<=e.clientWidth+1));
 if(width===1280)await page.screenshot({path:'/tmp/hc-preparation-integree.png',fullPage:true});L.check(width+' sans exception JS',errors.length===0);await page.close();}
 }finally{await browser.close();}process.exitCode=L.results()?1:0;
})().catch(e=>{console.error(e);process.exitCode=1});
