// Recette isolée PostgreSQL/WASM. Métadonnées de schéma uniquement, aucun client réel.
const fs=require('fs'),assert=require('assert');
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const planner=require('../assets/preparation-missions.js');
(async()=>{
 const db=new PGlite();const fixture=JSON.parse(fs.readFileSync(process.env.HC_SCHEMA_FIXTURE||require('path').join(__dirname,'preparation/schema.json'),'utf8'));
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function auth.jwt() returns jsonb language sql stable as $$select jsonb_build_object('role',current_user)$$;
 create function auth.email() returns text language sql stable as $$select 'qa@example.test'::text$$;
 grant usage on schema public,auth to authenticated,anon;grant execute on all functions in schema auth to authenticated,anon;`);
 for(const t of fixture.tables){for(const c of t.columns){const seq=c.default?.match(/nextval\('([^']+)'/);if(seq)await db.exec('create sequence if not exists '+seq[1]);}
 await db.exec('create table public.'+t.name+'('+t.columns.map(c=> '"'+c.name+'" '+c.type+(c.default?' default '+c.default:'')+(c.notnull?' not null':'')).join(',')+',primary key(id))');}
 await db.exec(`alter table missions add constraint missions_type_mission_check check(type_mission in ('convoyage','nettoyage'));
 alter table opportunites add unique(mission_id);alter table opportunite_candidatures add unique(opportunite_id,convoyeur_id);
 create unique index missions_devis_vehicule_unique on missions(devis_source_id,vehicule_source_id) where devis_source_id is not null;
 create unique index missions_nettoyage_une_par_demande on missions(client_id) where type_mission='nettoyage' and statut<>'annulee';
 create table test_infos(client_id uuid,statut text);
 create function informations_demande(p_client_id uuid) returns table(statut text) language sql as $$select statut from test_infos where client_id=p_client_id$$;`);
 for(const f of fixture.functions)await db.exec(f.sql);
 for(const v of fixture.views)await db.exec('create view '+v.name+' as '+v.sql);
 await db.exec(`create trigger trg_brouillon_opportunite_apres_mission after insert on missions for each row execute function brouillon_opportunite_apres_mission();
 create trigger garde_execution_paiement before insert or update on missions for each row execute function garder_publication_paiement();
 create trigger garde_publication_paiement before insert or update on opportunites for each row execute function garder_publication_paiement();
 create trigger verrou_opp before update on opportunites for each row execute function verrou_opportunite();
 create trigger synchroniser_brouillon_vehicule_test after update on vehicules for each row execute function synchroniser_brouillon_vehicule_test();`);
 const migration=fs.readdirSync('supabase/migrations').find(x=>x.endsWith('_preparation_missions_devis.sql'));
 await db.exec(fs.readFileSync('supabase/migrations/'+migration,'utf8'));
 const remiseMigration=fs.readdirSync('supabase/migrations').find(x=>x.endsWith('_point_remise_sans_enseigne.sql'));
 if(remiseMigration)await db.exec(fs.readFileSync('supabase/migrations/'+remiseMigration,'utf8'));
 await db.exec("create schema if not exists private;");
 await db.exec(fs.readFileSync('migrations/92_creation_demande_atomique.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20261009142317_restitution_destination_retour.sql','utf8'));
 const admin='11111111-1111-4111-8111-111111111111',cid='22222222-2222-4222-8222-222222222222',did='33333333-3333-4333-8333-333333333333',vid='44444444-4444-4444-8444-444444444444';
 await db.query("insert into admins(id,auth_user_id,email,actif) values(gen_random_uuid(),$1,'qa@example.test',true)",[admin]);
 await db.query("insert into clients(id,numero_client,code_parrainage,nom,prenom,email,type_service) values($1,'HC-RETOUR','QA-RETOUR','Client','Test','qa@example.test','convoyage')",[cid]);
 await db.query("insert into devis(id,client_id,reference,prix,statut,paiement_statut) values($1,$2,'DEV-QA',500,'accepte','paye')",[did,cid]);
 await db.query("insert into vehicules(id,dossier_id,position,type_vehicule,marque_modele,immatriculation,vin,ville_depart,ville_arrivee,date_prise_en_charge,date_livraison,heure_prise_en_charge,heure_livraison,adresse_depart_rue,adresse_arrivee_rue) values($1,$2,1,'berline','Tesla','AB-123-CD','VF123456789012345','Paris','Lyon','2026-11-08','2026-11-08','09:00','16:00','12 rue Départ','13 rue Livraison')",[vid,cid]);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[admin]);
 const rpc=async(name,args)=>(await db.query('select public.'+name+'('+args.map((_,i)=>'$'+(i+1)).join(',')+') r',args)).rows[0].r;
 const before=await rpc('source_preparation_missions',[cid]);
 await db.exec(fs.readFileSync('supabase/migrations/20261009144826_restitution_rendezvous_distincts.sql','utf8'));
 assert.equal((await rpc('source_preparation_missions',[cid])).empreinte,before.empreinte,'empreinte existante conservée');
 await db.query("update vehicules set restit_destination='stockage',restitution_concernee=true,restit_recuperation_client=true,restit_date='2026-11-09',restit_heure_type='creneau',restit_creneau_debut='10:00',restit_creneau_fin='12:00',restit_contact_nom='SECRET-CLIENT',restit_contact_tel='0600000000',restit_marque_modele='Renault Clio',restit_immatriculation='CD-456-EF',restit_vin='VIN-RETOUR' where id=$1",[vid]);
 let source=await rpc('source_preparation_missions',[cid]),plans=planner.build(source.client,source.vehicules,source.point_remise),p=plans[0];
 assert(p.retour_helixcar);assert.equal(p.mission.date_restitution_depart,null);assert(!JSON.stringify(planner.publicData(p)).includes('SECRET-CLIENT'));
 p.remuneration=150;p.motorisation='Hybride';p.restit_motorisation='Essence';p.distance=400;
 const save=async()=>{p.public=planner.publicData(p);return rpc('enregistrer_preparation_missions',[cid,source.empreinte,JSON.stringify(plans)]);};
 let saved=await save(),pid=saved.brouillons[0].id;
 await assert.rejects(rpc('publier_preparation_mission',[pid]),/deux rendez-vous/);
 p.retour_reception='2026-11-08T15:00';await assert.rejects(save(),/suivre la livraison/);
 p.retour_reception='2026-11-08T21:00';p.retour_remise='2026-11-08T20:00';await assert.rejects(save(),/suivre la réception/);
 p.retour_remise='2026-11-09T09:00';await assert.rejects(save(),/créneau/);
 p.retour_remise='2026-11-09T11:00';saved=await save();
 assert.match(saved.brouillons[0].plan.mission.date_restitution_depart,/2026-11-08T21:00/);
 assert(saved.brouillons[0].annonce.rows.some(r=>r.label==='Restitution prévue'&&r.value.includes('21:00')));
 const pub=await rpc('publier_preparation_mission',[pid]);
 const mission=(await db.query('select date_restitution_depart,restit_contact_nom from missions where id=$1',[pub.mission_id])).rows[0];
 assert.equal(new Intl.DateTimeFormat('fr-FR',{timeZone:'Europe/Paris',hour:'2-digit',hourCycle:'h23'}).format(new Date(mission.date_restitution_depart)),'21 h');assert.equal(mission.restit_contact_nom,'HelixCar');
 await db.exec('grant select on public.missions to authenticated;set role authenticated');
 const act=(kind,rev)=>rpc('action_restitution_helixcar',[pid,kind,rev]);
 await assert.rejects(act('confirmer_remise',0),/Confirmez d’abord/);
 let r=await act('confirmer_reception',0);assert.equal(r.revision,1);
 await assert.rejects(act('recevoir',0),/planning a changé/);
 r=await act('confirmer_remise',1);assert.equal(r.revision,2);
 await assert.rejects(act('remettre',2),/Réceptionnez/);
 r=await act('recevoir',2);assert(r.reception_effectuee_le&&!r.remise_effectuee_le);
 r=await act('remettre',3);assert(r.remise_effectuee_le&&r.reception_par===admin);
 await db.exec('reset role');
 await db.exec("select set_config('request.jwt.claim.sub','55555555-5555-4555-8555-555555555555',false);set role authenticated");
 assert.equal((await db.query('select * from planning_restitutions')).rows.length,0);await assert.rejects(act('confirmer_reception',4),/Accès réservé/);
 await db.exec('reset role;set role anon');await assert.rejects(db.query('select * from planning_restitutions'),/permission/);await assert.rejects(act('recevoir',4),/permission/);
 await db.exec('reset role');
 await db.query("update vehicules set restitution_concernee=false where id=$1",[vid]);
 assert.equal((await db.query('select restit_recuperation_client from vehicules where id=$1',[vid])).rows[0].restit_recuperation_client,false);
 console.log('PASS SQL : brouillons existants, convoyage avec retour HelixCar, chronologie, publication, deux rendez-vous, transitions, concurrence, RLS client/anonyme');
 await db.close();
})().catch(e=>{console.error(e.message,e.detail||'',e.where||'',e.stack);process.exitCode=1;});
