const fs=require('fs'),path=require('path');
module.exports=async({db,rpc,check,rejected,admin,cid,vid,uid,cv,pub})=>{
 await db.exec(`select set_config('request.jwt.claim.sub','${admin}',false);
 create table demande_informations_manquantes(client_id uuid,cle text,libelle text,statut text,valeur text,commentaire text,unique(client_id,cle));
 create function est_proprietaire_demande(uuid) returns boolean language sql as $$select false$$;
 create function hc_texte(p jsonb,variadic k text[]) returns text language sql immutable as $$select nullif(btrim(p #>> k),'')$$;
 create view v_mes_demandes as select id,vin from clients;
 drop function informations_demande(uuid);`);
 for(const sql of Object.values(require('./baseline.json')))await db.exec(sql);
 const file=fs.readdirSync('supabase/migrations').find(x=>x.endsWith('_motorisation_vehicules.sql'));
 await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8'));
 await db.exec(`create trigger synchroniser_information_validee after insert or update on demande_informations_manquantes for each row execute function synchroniser_information_validee();`);
 let infos=await db.query('select * from informations_demande($1)',[cid]);
 check('motorisation absente : information attendue',infos.rows.some(x=>x.cle==='vehicule_1_motorisation'&&x.statut==='attendue'));
 check('VIN conserve sa règle',infos.rows.some(x=>x.cle==='vehicule_1_vin'&&x.statut==='fournie'));
 check('liste blanche véhicule et demande', (await db.query("select 'motorisation'=any(champs_publics_vehicule()) and 'motorisation'=any(champs_publics_demande()) as ok")).rows[0].ok);
 await rejected('valeur inconnue rejetée côté base',()=>db.query("update vehicules set motorisation='inconnue' where id=$1",[vid]));
 await rejected('valeur inconnue rejetée en complétion',()=>rpc('verifier_valeur_information',['vehicule_1_motorisation','inconnue']));
 await db.query("insert into demande_informations_manquantes values($1,'vehicule_1_motorisation','Motorisation','transmise','Électrique',null)",[cid]);
 check('transmission attend validation',(await db.query('select * from informations_demande($1)',[cid])).rows.some(x=>x.cle==='vehicule_1_motorisation'&&x.statut==='transmise'));
 await db.query("update demande_informations_manquantes set statut='validee' where client_id=$1 and cle='vehicule_1_motorisation'",[cid]);
 check('validation reporte la motorisation au véhicule',(await db.query('select motorisation from vehicules where id=$1',[vid])).rows[0].motorisation==='Électrique');
 await db.query("update vehicules set restitution_concernee=true where id=$1",[vid]);
 check('restitution réclame sa propre motorisation',(await db.query('select * from informations_demande($1)',[cid])).rows.some(x=>x.cle==='vehicule_1_restit_motorisation'&&x.statut==='attendue'));
 await db.query("insert into demande_informations_manquantes values($1,'vehicule_1_restit_motorisation','Restitution','validee','Diesel',null)",[cid]);
 check('motorisation de restitution indépendante',(await db.query('select restit_motorisation from vehicules where id=$1',[vid])).rows[0].restit_motorisation==='Diesel');
 await db.query("insert into demande_informations_manquantes values($1,'motorisation','Motorisation','validee','Hybride',null)",[cid]);
 check('compatibilité mono : valeur synchronisée',(await db.query('select motorisation from clients where id=$1',[cid])).rows[0].motorisation==='Hybride');
 check('vue client expose la valeur',(await db.query('select motorisation from v_mes_demandes where id=$1',[cid])).rows[0].motorisation==='Hybride');
 await db.exec("insert into missions(id,reference,type_mission,ville_depart,ville_arrivee,statut) values(gen_random_uuid(),'QA-LEG-CONV','convoyage','Paris','Lyon','en_attente'),(gen_random_uuid(),'QA-LEG-NET','nettoyage','','','en_attente');");
 const renfort=(await db.query("insert into missions(id,reference,type_mission,ville_depart,ville_arrivee,statut) values(gen_random_uuid(),'QA-RENFORT','professionnel','','','en_attente') returning id")).rows[0].id;
 const ro=(await db.query('select id from opportunites where mission_id=$1',[renfort])).rows[0].id;
 await db.query("update opportunites set categorie='renfort',badges_requis=array['renfort'],description_publique='Intervention',intitule='Renfort automobile' where id=$1",[ro]);
 await rpc('publier_opportunite',[ro]);
 for(const cat of ['convoyage','nettoyage','technicien','renfort']){
  await db.query('delete from convoyeur_decisions where convoyeur_id=$1',[cv]);
  await db.query("insert into convoyeur_decisions(convoyeur_id,activite,decision) values($1,$2,'oui')",[cv,cat]);
  await db.exec(`select set_config('request.jwt.claim.sub','${uid}',false);set role authenticated;`);
  check('missions disponibles : badge '+cat,(await db.query("select type_mission from missions where reference like 'QA-LEG-%'")).rows.every(m=>m.type_mission===cat));
  const ops=(await db.query('select * from v_opportunites_partenaire')).rows;
  check('badge '+cat+' : seules les annonces du métier',ops.every(o=>o.categorie===cat)&&ops.length>0);
  await db.exec('reset role');
  if(cat!=='convoyage')check('badge '+cat+' : candidature convoyage refusée',(await rpc('postuler_opportunite',[pub.opportunite_id])).code==='NON_ELIGIBLE');
  await db.exec(`select set_config('request.jwt.claim.sub','${admin}',false);`);
 }
 await db.query("insert into convoyeur_decisions(convoyeur_id,activite,decision) values($1,'nettoyage','oui')",[cv]);
 await db.exec(`select set_config('request.jwt.claim.sub','${uid}',false);set role authenticated;`);
 check('multi-badges : accès aux métiers validés',(await db.query('select * from v_opportunites_partenaire')).rows.some(o=>o.categorie==='nettoyage'));
 await db.exec('reset role');
};
